name: publish


on:
  push:
    branches: ["android"]


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build android
        run: sudo docker build . -t lazypanda07/ubuntu_cxx20:android
          
      - name: Push android
        run: |
            sudo docker login -u "${{ secrets.DOCKER_HUB_LOGIN }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
            sudo docker push lazypanda07/ubuntu_cxx20:android
          