name: publish


on:
  push:
    branches: ["24.04"]


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build 24.04
        run: sudo docker build . -t lazypanda07/ubuntu_cxx20:24.04
          
      - name: Push 24.04
        run: |
            sudo docker login -u "${{ secrets.DOCKER_HUB_LOGIN }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
            sudo docker push lazypanda07/ubuntu_cxx20:24.04
          