name: publish


on:
  push:
    branches: ["24.04"]


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build 24.04
        run: sudo docker build . -t lazypanda07/ubuntu_cxx20:24.04
          
      - name: Push 24.04
        run: sudo docker push lazypanda07/ubuntu_cxx20:24.04
          